name: Deploy pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.x
          cache: pip

      - name: Setup ctfcli
        run: |
          pip install -r requirements.txt
          
          mkdir .ctf
          cat <<EOF > .ctf/config
          [config]
          url = https://${{ vars.CTFD_DOMAIN }}
          access_token = ${{ secrets.CTFD_TOKEN }}

          [cookies]
          site_password = ${{ secrets.CTFD_SITE_PASSWORD }}

          [challenges]
          EOF

      - name: Deploy pages
        run: ctf pages sync
